#!/bin/bash

curl -o database.csv 'https://wfs.geonet.org.nz/geonet/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geonet:quake_search_v1&maxFeatures=50&outputFormat=csv'

(cat - | sqlite3 database.db) << EOF
.mode csv
.import database.csv quakes
EOF
